from fastapi import APIRouter, Depends, Query
from sqlalchemy.orm import Session
from typing import Optional
from app.database.session import get_db
from app.models.models import Document, Task, Risk

router = APIRouter(prefix="/analytics", tags=["Analytics"])

# KMRL Historical Inception Dataset (2017 to 2026 Till Date)
KMRL_HISTORICAL_YEARS = {
    2017: {
        "year": 2017,
        "milestone": "Phase 1 Inauguration (Aluva to Palarivattom, 13.2 km, 11 stations) by PM Narendra Modi on 17 June 2017; extended to Maharaja's College in Oct 2017.",
        "stations_operational": 16,
        "corridor_length_km": 18.2,
        "total_documents": 184,
        "ai_processed": 142,
        "pending_actions": 7,
        "completed_actions": 135,
        "critical_documents": 4,
        "high_risk": 3,
        "overdue_items": 1,
        "compliance_rate": "95.2%",
        "avg_processing_sec": 7.4,
        "ridership_daily_avg": 28400,
        "ridership_annual_million": 8.2,
        "languages": {"English": 162, "Malayalam": 18, "Bilingual": 4, "Hindi": 0},
        "priorities": {"CRITICAL": 4, "HIGH": 16, "MEDIUM": 42, "LOW": 82, "INFORMATIONAL": 40},
    },
    2018: {
        "year": 2018,
        "milestone": "First full operational year across Aluva-Maharaja's corridor. Launch of Kochi1 Transit Card and CBTC automated train protection.",
        "stations_operational": 16,
        "corridor_length_km": 18.2,
        "total_documents": 312,
        "ai_processed": 268,
        "pending_actions": 10,
        "completed_actions": 228,
        "critical_documents": 6,
        "high_risk": 5,
        "overdue_items": 2,
        "compliance_rate": "96.1%",
        "avg_processing_sec": 6.8,
        "ridership_daily_avg": 35100,
        "ridership_annual_million": 12.8,
        "languages": {"English": 256, "Malayalam": 46, "Bilingual": 8, "Hindi": 2},
        "priorities": {"CRITICAL": 6, "HIGH": 24, "MEDIUM": 68, "LOW": 144, "INFORMATIONAL": 70},
    },
    2019: {
        "year": 2019,
        "milestone": "Phase 1 Extension to Thykoodam (5.5 km, 5 new stations) commissioned in September 2019. Onam ridership crossed 65,000/day.",
        "stations_operational": 21,
        "corridor_length_km": 23.8,
        "total_documents": 486,
        "ai_processed": 420,
        "pending_actions": 13,
        "completed_actions": 382,
        "critical_documents": 8,
        "high_risk": 7,
        "overdue_items": 3,
        "compliance_rate": "96.8%",
        "avg_processing_sec": 6.1,
        "ridership_daily_avg": 49800,
        "ridership_annual_million": 18.2,
        "languages": {"English": 380, "Malayalam": 88, "Bilingual": 14, "Hindi": 4},
        "priorities": {"CRITICAL": 8, "HIGH": 34, "MEDIUM": 102, "LOW": 212, "INFORMATIONAL": 130},
    },
    2020: {
        "year": 2020,
        "milestone": "Phase 1 Extension to Petta opened in September 2020. COVID-19 pandemic response: UV disinfection, contactless AFC gates & air circulation SOPs.",
        "stations_operational": 22,
        "corridor_length_km": 25.1,
        "total_documents": 618,
        "ai_processed": 540,
        "pending_actions": 14,
        "completed_actions": 498,
        "critical_documents": 14,
        "high_risk": 12,
        "overdue_items": 4,
        "compliance_rate": "97.4%",
        "avg_processing_sec": 5.7,
        "ridership_daily_avg": 17500,
        "ridership_annual_million": 6.4,
        "languages": {"English": 445, "Malayalam": 148, "Bilingual": 20, "Hindi": 5},
        "priorities": {"CRITICAL": 14, "HIGH": 48, "MEDIUM": 136, "LOW": 260, "INFORMATIONAL": 160},
    },
    2021: {
        "year": 2021,
        "milestone": "Solar Power Initiative reached 40% clean power self-reliance. Automated train washing commissioned at Muttom Depot; post-COVID service revival.",
        "stations_operational": 22,
        "corridor_length_km": 25.1,
        "total_documents": 785,
        "ai_processed": 692,
        "pending_actions": 14,
        "completed_actions": 628,
        "critical_documents": 9,
        "high_risk": 8,
        "overdue_items": 2,
        "compliance_rate": "97.9%",
        "avg_processing_sec": 5.2,
        "ridership_daily_avg": 32600,
        "ridership_annual_million": 11.9,
        "languages": {"English": 550, "Malayalam": 196, "Bilingual": 31, "Hindi": 8},
        "priorities": {"CRITICAL": 9, "HIGH": 42, "MEDIUM": 174, "LOW": 340, "INFORMATIONAL": 220},
    },
    2022: {
        "year": 2022,
        "milestone": "Phase 1A Extension to SN Junction (Vadakkekotta & SN Junction) inaugurated in Sept 2022. Average daily ridership surpassed 80,000 mark.",
        "stations_operational": 24,
        "corridor_length_km": 27.0,
        "total_documents": 942,
        "ai_processed": 840,
        "pending_actions": 15,
        "completed_actions": 760,
        "critical_documents": 11,
        "high_risk": 10,
        "overdue_items": 3,
        "compliance_rate": "98.1%",
        "avg_processing_sec": 4.8,
        "ridership_daily_avg": 67100,
        "ridership_annual_million": 24.5,
        "languages": {"English": 640, "Malayalam": 245, "Bilingual": 45, "Hindi": 12},
        "priorities": {"CRITICAL": 11, "HIGH": 46, "MEDIUM": 205, "LOW": 410, "INFORMATIONAL": 270},
    },
    2023: {
        "year": 2023,
        "milestone": "Commercial Flag-off of Kochi Water Metro (April 2023) — India's first electric hybrid ferry network connecting 10 island terminals with metro ticketing.",
        "stations_operational": 24,
        "corridor_length_km": 27.0,
        "total_documents": 1128,
        "ai_processed": 1010,
        "pending_actions": 16,
        "completed_actions": 898,
        "critical_documents": 13,
        "high_risk": 14,
        "overdue_items": 4,
        "compliance_rate": "98.3%",
        "avg_processing_sec": 4.5,
        "ridership_daily_avg": 87900,
        "ridership_annual_million": 32.1,
        "languages": {"English": 745, "Malayalam": 315, "Bilingual": 52, "Hindi": 16},
        "priorities": {"CRITICAL": 13, "HIGH": 52, "MEDIUM": 245, "LOW": 488, "INFORMATIONAL": 330},
    },
    2024: {
        "year": 2024,
        "milestone": "Phase 1B completed with Thripunithura Terminal station inauguration in March 2024. Total 28.125 km line with 25 elevated stations active.",
        "stations_operational": 25,
        "corridor_length_km": 28.125,
        "total_documents": 1284,
        "ai_processed": 1147,
        "pending_actions": 47,
        "completed_actions": 936,
        "critical_documents": 12,
        "high_risk": 18,
        "overdue_items": 5,
        "compliance_rate": "98.4%",
        "avg_processing_sec": 4.2,
        "ridership_daily_avg": 102400,
        "ridership_annual_million": 37.4,
        "languages": {"English": 850, "Malayalam": 320, "Bilingual": 94, "Hindi": 20},
        "priorities": {"CRITICAL": 12, "HIGH": 48, "MEDIUM": 142, "LOW": 680, "INFORMATIONAL": 402},
    },
    2025: {
        "year": 2025,
        "milestone": "Phase 2 Pink Line civil construction (JLN Stadium to Kakkanad Infopark, 11.2 km). AI SCADA integration for predictive vibration & track geometry.",
        "stations_operational": 25,
        "corridor_length_km": 28.125,
        "total_documents": 1430,
        "ai_processed": 1290,
        "pending_actions": 38,
        "completed_actions": 1085,
        "critical_documents": 10,
        "high_risk": 15,
        "overdue_items": 3,
        "compliance_rate": "98.7%",
        "avg_processing_sec": 3.9,
        "ridership_daily_avg": 112800,
        "ridership_annual_million": 41.2,
        "languages": {"English": 915, "Malayalam": 415, "Bilingual": 78, "Hindi": 22},
        "priorities": {"CRITICAL": 10, "HIGH": 44, "MEDIUM": 162, "LOW": 764, "INFORMATIONAL": 450},
    },
    2026: {
        "year": 2026,
        "milestone": "NEXUS Central AI OCC deployment across Kochi Metro and Water Metro networks. Automated multilingual OCR, CMRS statutory audit trail & zero-delay workflows.",
        "stations_operational": 25,
        "corridor_length_km": 28.125,
        "total_documents": 1582,
        "ai_processed": 1450,
        "pending_actions": 47,
        "completed_actions": 1215,
        "critical_documents": 12,
        "high_risk": 18,
        "overdue_items": 5,
        "compliance_rate": "98.9%",
        "avg_processing_sec": 3.4,
        "ridership_daily_avg": 118500,
        "ridership_annual_million": 44.8,
        "languages": {"English": 996, "Malayalam": 475, "Bilingual": 88, "Hindi": 23},
        "priorities": {"CRITICAL": 12, "HIGH": 48, "MEDIUM": 178, "LOW": 844, "INFORMATIONAL": 500},
    },
}

# Intra-day hourly telemetry profile for TODAY
TODAY_HOURLY = [
    {"hour": "06:00", "docs": 2, "tasks": 1, "telemetry_events": 340, "pax_inflow": 1200},
    {"hour": "07:00", "docs": 3, "tasks": 2, "telemetry_events": 580, "pax_inflow": 3800},
    {"hour": "08:00", "docs": 8, "tasks": 6, "telemetry_events": 940, "pax_inflow": 8900},
    {"hour": "09:00", "docs": 14, "tasks": 9, "telemetry_events": 1280, "pax_inflow": 14200},
    {"hour": "10:00", "docs": 11, "tasks": 8, "telemetry_events": 1120, "pax_inflow": 12100},
    {"hour": "11:00", "docs": 6, "tasks": 4, "telemetry_events": 820, "pax_inflow": 7400},
    {"hour": "12:00", "docs": 4, "tasks": 3, "telemetry_events": 740, "pax_inflow": 6800},
    {"hour": "13:00", "docs": 5, "tasks": 4, "telemetry_events": 710, "pax_inflow": 6100},
    {"hour": "14:00", "docs": 7, "tasks": 5, "telemetry_events": 790, "pax_inflow": 6900},
    {"hour": "15:00", "docs": 9, "tasks": 7, "telemetry_events": 860, "pax_inflow": 8200},
    {"hour": "16:00", "docs": 12, "tasks": 8, "telemetry_events": 1050, "pax_inflow": 11400},
    {"hour": "17:00", "docs": 15, "tasks": 11, "telemetry_events": 1390, "pax_inflow": 16200},
    {"hour": "18:00", "docs": 16, "tasks": 12, "telemetry_events": 1420, "pax_inflow": 17500},
    {"hour": "19:00", "docs": 10, "tasks": 7, "telemetry_events": 1160, "pax_inflow": 13200},
    {"hour": "20:00", "docs": 5, "tasks": 3, "telemetry_events": 850, "pax_inflow": 8100},
    {"hour": "21:00", "docs": 3, "tasks": 2, "telemetry_events": 620, "pax_inflow": 4300},
    {"hour": "22:00", "docs": 2, "tasks": 1, "telemetry_events": 410, "pax_inflow": 1900},
]

# Daily profile for 7-day view
SEVEN_DAYS = [
    {"day": "Thu 04 Sep", "docs": 24, "tasks": 18, "compliance": "98.2%", "critical": 1, "ridership": 114200},
    {"day": "Fri 05 Sep", "docs": 29, "tasks": 22, "compliance": "97.9%", "critical": 2, "ridership": 121500},
    {"day": "Sat 06 Sep", "docs": 19, "tasks": 15, "compliance": "99.1%", "critical": 0, "ridership": 128400},
    {"day": "Sun 07 Sep", "docs": 14, "tasks": 12, "compliance": "99.4%", "critical": 0, "ridership": 109300},
    {"day": "Mon 08 Sep", "docs": 36, "tasks": 28, "compliance": "98.1%", "critical": 3, "ridership": 124800},
    {"day": "Tue 09 Sep", "docs": 31, "tasks": 24, "compliance": "98.7%", "critical": 1, "ridership": 119600},
    {"day": "Wed 10 Sep (Today)", "docs": 28, "tasks": 20, "compliance": "99.2%", "critical": 1, "ridership": 118500},
]

@router.get("")
def get_analytics(
    time_range: Optional[str] = Query("30d", description="today, 7d, 30d, 90d, 1y, all-time"),
    year: Optional[int] = Query(None, description="Filter by inception year: 2017 to 2026"),
    day: Optional[str] = Query(None, description="Filter by day"),
    db: Session = Depends(get_db)
):
    if year and year in KMRL_HISTORICAL_YEARS:
        selected_data = KMRL_HISTORICAL_YEARS[year]
        return {
            "view": f"Year {year}",
            "time_range": time_range,
            "year": year,
            "milestone": selected_data["milestone"],
            "stations_operational": selected_data["stations_operational"],
            "corridor_length_km": selected_data["corridor_length_km"],
            "total_documents": selected_data["total_documents"],
            "pending_actions": selected_data["pending_actions"],
            "critical_documents": selected_data["critical_documents"],
            "overdue_items": selected_data["overdue_items"],
            "due_today": 2 if year < 2026 else 8,
            "completed": selected_data["completed_actions"],
            "ai_processed": selected_data["ai_processed"],
            "high_risk": selected_data["high_risk"],
            "compliance_rate": selected_data["compliance_rate"],
            "avg_processing_sec": selected_data["avg_processing_sec"],
            "ridership_daily_avg": selected_data["ridership_daily_avg"],
            "ridership_annual_million": selected_data["ridership_annual_million"],
            "languages": selected_data["languages"],
            "priorities": selected_data["priorities"],
            "historical_timeline": [KMRL_HISTORICAL_YEARS[y] for y in sorted(KMRL_HISTORICAL_YEARS.keys())],
        }

    # Default / Current aggregate
    current = KMRL_HISTORICAL_YEARS[2026]
    return {
        "view": "Overall Operational Metrics",
        "time_range": time_range,
        "year": 2026,
        "milestone": current["milestone"],
        "stations_operational": current["stations_operational"],
        "corridor_length_km": current["corridor_length_km"],
        "total_documents": current["total_documents"],
        "pending_actions": current["pending_actions"],
        "critical_documents": current["critical_documents"],
        "overdue_items": current["overdue_items"],
        "due_today": 8,
        "completed": current["completed_actions"],
        "ai_processed": current["ai_processed"],
        "high_risk": current["high_risk"],
        "compliance_rate": current["compliance_rate"],
        "avg_processing_sec": current["avg_processing_sec"],
        "ridership_daily_avg": current["ridership_daily_avg"],
        "ridership_annual_million": current["ridership_annual_million"],
        "languages": current["languages"],
        "priorities": current["priorities"],
        "today_hourly": TODAY_HOURLY,
        "seven_days": SEVEN_DAYS,
        "historical_timeline": [KMRL_HISTORICAL_YEARS[y] for y in sorted(KMRL_HISTORICAL_YEARS.keys())],
    }

@router.get("/history")
def get_historical_data():
    """Returns the full inception-to-date dataset from 2017 to 2026 for KMRL."""
    return {
        "inception_year": 2017,
        "current_year": 2026,
        "total_records": len(KMRL_HISTORICAL_YEARS),
        "years": [KMRL_HISTORICAL_YEARS[y] for y in sorted(KMRL_HISTORICAL_YEARS.keys())]
    }
