import { DocumentItem, TaskItem, ExtractedRisk, DocumentConflict, NotificationItem, AuditLogItem, RiskSeverity, RiskCategory } from '../types';

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'DOC-KMRL-2026-001',
    title: 'Aluva Station Fire Safety Audit & Sprinkler System Overhaul',
    fileName: 'KMRL_SFT_ALUVA_FIRE_2026.pdf',
    fileType: 'PDF',
    fileSize: '4.8 MB',
    department: 'Safety',
    language: 'English',
    aiPriority: 'CRITICAL',
    status: 'PROCESSED',
    aiConfidence: 97,
    aiPriorityReason: 'Document mandates immediate shutdown inspection of the main passenger concourse sprinkler loop due to sensor pressure drops below 2.4 bar, with regulatory compliance deadline within 24 hours.',
    summary: 'Comprehensive audit revealing pressure degradation in the Aluva Station platform-level fire suppression grid. Requires physical hydraulic testing, certification from Ernakulam District Fire Force, and recalibration of flow meters before passenger operations tomorrow.',
    keyFacts: [
      'Aluva platform 2 sprinkler line pressure dropped from 4.2 bar to 2.1 bar',
      'Non-compliance with National Building Code (NBC 2016) Metro Annexure IV',
      'Mandatory physical re-inspection ordered within 24 hours',
      'Responsible Officer: S. Pradeep (Chief Safety Inspector)',
    ],
    receivedDate: '2026-09-08T10:30:00Z',
    createdDate: '2026-09-08T09:00:00Z',
    submissionDeadline: '2026-09-10T12:00:00Z',
    expectedCompletion: '2026-09-10T18:00:00Z',
    assignedTo: 'S. Pradeep',
    riskScore: 94,
    station: 'Aluva',
    storagePath: 'Safety/2026/KMRL_SFT_ALUVA_FIRE_2026.pdf',
    timeline: [
      { date: '08 Sep 2026, 10:30 AM', stage: 'Document Received', description: 'Transmitted via Kerala Fire & Rescue Services portal', status: 'completed' },
      { date: '08 Sep 2026, 10:32 AM', stage: 'AI Ingested & OCR', description: 'Extracted 14 pages of technical telemetry tables', status: 'completed' },
      { date: '08 Sep 2026, 10:33 AM', stage: 'Priority Classified', description: 'Assigned CRITICAL priority (97% confidence)', status: 'completed' },
      { date: '08 Sep 2026, 10:35 AM', stage: 'Tasks Dispatched', description: 'Auto-routed to Safety and Operations departments', status: 'completed' },
      { date: '10 Sep 2026, 12:00 PM', stage: 'Statutory Deadline', description: 'Compliance submission required to CMRS', status: 'current' },
    ],
    entities: [
      { id: 'ENT-01', name: 'Aluva Metro Station', type: 'STATION', occurrences: 19 },
      { id: 'ENT-02', name: 'Safety Directorate', type: 'DEPARTMENT', occurrences: 14 },
      { id: 'ENT-03', name: 'National Building Code 2016', type: 'POLICY', occurrences: 6 },
      { id: 'ENT-04', name: 'S. Pradeep', type: 'OFFICER', occurrences: 8 },
      { id: 'ENT-05', name: 'CMRS Kerala Circle', type: 'REGULATION', occurrences: 5 },
    ],
    actions: [
      {
        id: 'ACT-001',
        task: 'Execute pressure sensor recalibration on Aluva Concourse Line 2',
        department: 'Safety',
        assignedPerson: 'S. Pradeep',
        priority: 'CRITICAL',
        deadline: '2026-09-10T12:00:00Z',
        status: 'IN_PROGRESS',
        evidenceRequired: 'Fire Marshal calibration test certificate and digital manometer gauge readings',
        sourceReference: 'Page 4, Section 3.2',
      },
      {
        id: 'ACT-002',
        task: 'Conduct joint physical inspection with Ernakulam Fire Station Officer',
        department: 'Operations',
        assignedPerson: 'Deepa Menon',
        priority: 'HIGH',
        deadline: '2026-09-10T16:00:00Z',
        status: 'PENDING',
        evidenceRequired: 'Joint inspection clearance protocol countersigned by Station Controller',
        sourceReference: 'Page 8, Clause 6.1',
      },
    ],
    risks: [
      {
        id: 'RSK-001',
        title: 'Aluva Platform Sprinkler Failure Risk',
        description: 'Insufficient water curtain flow rate in emergency evacuation zone.',
        severity: 'CRITICAL',
        category: 'SAFETY',
        station: 'Aluva',
        recommendedMitigation: 'Isolate loop valve 4B and pressurize backup diesel pump feed immediately.',
        sourceReference: 'Page 2, Executive Summary',
      },
    ],
    rawContentSnippet: 'URGENT CIRCULAR: Notice under Section 28 of Metro Railways Act. Inspection revealed sprinkler pressure deficiency at Aluva station concourse. Compliance report must be filed within 24 hours to avoid passenger halt order.',
  },
  {
    id: 'DOC-KMRL-2026-002',
    title: 'റോളിംഗ് സ്റ്റോക്ക് ബ്രേക്ക് പാഡ് മാറ്റിസ്ഥാപിക്കൽ നിർദ്ദേശം (Bilingual Rolling Stock Directive)',
    fileName: 'KMRL_RS_BRAKE_CIRCULAR_ML.pdf',
    fileType: 'PDF',
    fileSize: '3.2 MB',
    department: 'Maintenance',
    language: 'Bilingual (EN/ML)',
    aiPriority: 'HIGH',
    status: 'PROCESSED',
    aiConfidence: 94,
    aiPriorityReason: 'Bilingual technical circular identifying wear patterns on Alstom Metropolis 3-car rake composite brake pads exceeding 11mm threshold.',
    summary: 'മുട്ടം ഡിപ്പോയിലെ ട്രെയിൻ സെറ്റ് 04, 07 എന്നിവയുടെ ബ്രേക്ക് പാഡുകൾ അടിയന്തിരമായി പരിശോധിക്കാനും തേയ്മാനം 12 മില്ലീമീറ്ററിൽ കൂടുതലാണെങ്കിൽ മാറ്റിസ്ഥാപിക്കാനുമുള്ള ഔദ്യോഗിക ഉത്തരവ്. 48 മണിക്കൂറിനകം റിപ്പോർട്ട് സമർപ്പിക്കണം.',
    keyFacts: [
      'Applies to Alstom Metropolis trainsets 04 & 07 operating on Aluva-Petta corridor',
      'Maximum allowable wear: 10mm; measured wear on Set 07: 11.4mm',
      'Replacement depot: Muttom Depot Stabling Bay 4',
      'Target completion: 11 September 2026',
    ],
    receivedDate: '2026-09-08T14:15:00Z',
    createdDate: '2026-09-08T12:00:00Z',
    submissionDeadline: '2026-09-11T17:00:00Z',
    expectedCompletion: '2026-09-11T19:00:00Z',
    assignedTo: 'Rajesh Kumar Nair',
    riskScore: 82,
    station: 'Muttom Depot',
    storagePath: 'Maintenance/2026/KMRL_RS_BRAKE_CIRCULAR_ML.pdf',
    timeline: [
      { date: '08 Sep 2026, 02:15 PM', stage: 'Document Received', description: 'Depot Maintenance Superintendent Dispatch', status: 'completed' },
      { date: '08 Sep 2026, 02:18 PM', stage: 'Bilingual OCR & Translation', description: 'Malayalam script transcribed and verified with English technical table', status: 'completed' },
      { date: '08 Sep 2026, 02:20 PM', stage: 'Assigned to Rolling Stock', description: 'Assigned to Lead Engineer Rajesh Nair', status: 'completed' },
      { date: '11 Sep 2026, 05:00 PM', stage: 'Replacement Deadline', description: 'Mandatory certification before revenue service', status: 'current' },
    ],
    entities: [
      { id: 'ENT-06', name: 'Muttom Depot', type: 'STATION', occurrences: 16 },
      { id: 'ENT-07', name: 'Maintenance Directorate', type: 'DEPARTMENT', occurrences: 12 },
      { id: 'ENT-08', name: 'Trainset RS-07', type: 'ASSET', occurrences: 11 },
      { id: 'ENT-09', name: 'Rajesh Kumar Nair', type: 'OFFICER', occurrences: 5 },
    ],
    actions: [
      {
        id: 'ACT-003',
        task: 'Replace composite brake pad assemblies on Trainset 07 (Axles 1-6)',
        department: 'Maintenance',
        assignedPerson: 'Rajesh Kumar Nair',
        priority: 'HIGH',
        deadline: '2026-09-11T17:00:00Z',
        status: 'IN_PROGRESS',
        evidenceRequired: 'Brake torque verification test report & technician sign-off sheet',
        sourceReference: 'Page 3, Paragraph 2 (Malayalam Section)',
      },
    ],
    risks: [
      {
        id: 'RSK-002',
        title: 'Braking Distance Degradation on Wet Track Conditions',
        description: 'Friction coefficient drops during monsoon braking without pad replacement.',
        severity: 'HIGH',
        category: 'SAFETY',
        station: 'Muttom Depot',
        recommendedMitigation: 'Withdraw trainset 07 from peak-hour revenue service until overhaul.',
        sourceReference: 'Page 5, Technical Chart',
      },
    ],
    rawContentSnippet: 'മെട്രോ ട്രെയിൻ സെറ്റ് 07-ൽ ബ്രേക്ക് പാഡ് മാറ്റിസ്ഥാപിക്കൽ അടിയന്തിരമായി പൂർത്തിയാക്കുക. നിർദ്ദേശങ്ങൾ പാലിക്കാത്തപക്ഷം സർവീസ് പിൻവലിക്കാൻ ഉത്തരവിടുന്നു.',
  },
  {
    id: 'DOC-KMRL-2026-003',
    title: 'Traction Substation 25kV AC Overhead Catenary Inspection Protocol',
    fileName: 'KMRL_ENG_CATENARY_25KV_2026.pdf',
    fileType: 'PDF',
    fileSize: '6.1 MB',
    department: 'Engineering',
    language: 'English',
    aiPriority: 'CRITICAL',
    status: 'PROCESSED',
    aiConfidence: 98,
    aiPriorityReason: 'Inspection protocol mandates non-destructive ultrasonic testing of tension insulators between Kaloor and Edapally spans following lightning strike report.',
    summary: 'Detailed procedure for testing 25kV AC rigid catenary droppers and neutral section insulators between Kaloor Stadium and Edapally Station. Requires block grant of 2.5 hours during night shadow traffic hours.',
    keyFacts: [
      'Locations: Mast 124/10 to 128/20 between Kaloor and Edapally',
      'Lightning arrester counter triggered twice during 07 September storm',
      'Power block required: 01:15 AM to 03:45 AM',
      'Statutory requirement: RDSO Overhead Traction Standard 2024',
    ],
    receivedDate: '2026-09-07T18:00:00Z',
    createdDate: '2026-09-07T16:30:00Z',
    submissionDeadline: '2026-09-10T04:00:00Z',
    expectedCompletion: '2026-09-10T06:00:00Z',
    assignedTo: 'Anand Varma',
    riskScore: 91,
    station: 'Kaloor Stadium',
    storagePath: 'Engineering/2026/KMRL_ENG_CATENARY_25KV_2026.pdf',
    timeline: [
      { date: '07 Sep 2026, 06:00 PM', stage: 'Document Received', description: 'Traction SCADA automated anomaly log', status: 'completed' },
      { date: '07 Sep 2026, 06:05 PM', stage: 'AI Risk Analysis', description: 'Identified insulator micro-fracture hazard', status: 'completed' },
      { date: '08 Sep 2026, 09:00 AM', stage: 'Block Grant Approved', description: 'Operations granted 2.5h night track access', status: 'completed' },
      { date: '10 Sep 2026, 04:00 AM', stage: 'Completion Deadline', description: 'Overhead energization test clearance', status: 'current' },
    ],
    entities: [
      { id: 'ENT-10', name: 'Kaloor Stadium Station', type: 'STATION', occurrences: 15 },
      { id: 'ENT-11', name: 'Edapally Station', type: 'STATION', occurrences: 12 },
      { id: 'ENT-12', name: 'Engineering Directorate', type: 'DEPARTMENT', occurrences: 10 },
      { id: 'ENT-13', name: '25kV Catenary Line', type: 'ASSET', occurrences: 22 },
    ],
    actions: [
      {
        id: 'ACT-004',
        task: 'Execute night ultrasonic test on 25kV tension insulator span 126/14',
        department: 'Engineering',
        assignedPerson: 'Anand Varma',
        priority: 'CRITICAL',
        deadline: '2026-09-10T04:00:00Z',
        status: 'IN_PROGRESS',
        evidenceRequired: 'Ultrasonic flaw detector oscillogram waveform snapshot and insulation resistance megger log',
        sourceReference: 'Page 7, Testing Annexure B',
      },
    ],
    risks: [
      {
        id: 'RSK-003',
        title: 'Catenary Parting & Power Grid Trip Hazard',
        description: 'Damaged ceramic insulator could trigger line grounding during peak morning headway.',
        severity: 'CRITICAL',
        category: 'INFRASTRUCTURE',
        station: 'Kaloor Stadium',
        recommendedMitigation: 'Replace insulator cluster 126/14 tonight during scheduled power block.',
        sourceReference: 'Page 3, Technical Assessment',
      },
    ],
    rawContentSnippet: 'MANDATORY ACTION: Inspection of 25kV traction insulators following transient ground fault between Kaloor and Edapally. Night block testing is imperative before 10 September sunrise.',
  },
  {
    id: 'DOC-KMRL-2026-004',
    title: 'Edapally Station Escalator & Elevator Safety Compliance Audit 2026',
    fileName: 'KMRL_OPS_EDAPALLY_ESCALATOR_2026.pdf',
    fileType: 'PDF',
    fileSize: '3.9 MB',
    department: 'Operations',
    language: 'English',
    aiPriority: 'MEDIUM',
    status: 'PROCESSED',
    aiConfidence: 95,
    aiPriorityReason: 'Periodic statutory inspection of heavy-duty public transit escalators at Edapally (Exit B connecting to Lulu Mall walkway).',
    summary: 'ThyssenKrupp quarterly service report for 6 escalators and 4 glass elevators at Edapally Station. Step chain elongation within limits; comb plate sensor switch on Escalator 3 requires micro-switch replacement.',
    keyFacts: [
      'High passenger volume station (connecting Lulu Mall Skywalk)',
      'Escalator E-03 comb switch sensitivity out of alignment by 1.8mm',
      'No structural damage detected',
      'Deadline: 14 September 2026',
    ],
    receivedDate: '2026-09-06T11:00:00Z',
    createdDate: '2026-09-06T10:00:00Z',
    submissionDeadline: '2026-09-14T17:00:00Z',
    expectedCompletion: '2026-09-14T18:00:00Z',
    assignedTo: 'Geetha P.',
    riskScore: 48,
    station: 'Edapally',
    storagePath: 'Operations/2026/KMRL_OPS_EDAPALLY_ESCALATOR_2026.pdf',
    timeline: [
      { date: '06 Sep 2026, 11:00 AM', stage: 'Document Ingestion', description: 'Uploaded by ThyssenKrupp vendor portal', status: 'completed' },
      { date: '06 Sep 2026, 11:05 AM', stage: 'AI Entity Extraction', description: 'Matched Escalator E-03 asset tag', status: 'completed' },
      { date: '14 Sep 2026, 05:00 PM', stage: 'Work Order Target', description: 'Micro-switch replacement deadline', status: 'current' },
    ],
    entities: [
      { id: 'ENT-14', name: 'Edapally Station', type: 'STATION', occurrences: 18 },
      { id: 'ENT-15', name: 'Operations Directorate', type: 'DEPARTMENT', occurrences: 7 },
      { id: 'ENT-16', name: 'Escalator E-03', type: 'ASSET', occurrences: 9 },
    ],
    actions: [
      {
        id: 'ACT-005',
        task: 'Replace comb plate micro-switch and adjust safety skirt gap on Escalator 03',
        department: 'Operations',
        assignedPerson: 'Geetha P.',
        priority: 'MEDIUM',
        deadline: '2026-09-14T17:00:00Z',
        status: 'PENDING',
        evidenceRequired: 'Vendor work sign-off sheet with feeler gauge clearance measurements',
        sourceReference: 'Page 5, Clause 4.2',
      },
    ],
    risks: [
      {
        id: 'RSK-004',
        title: 'Passenger Footwear Entrapment Risk',
        description: 'Comb plate clearance exceeding 4mm could cause emergency trip on crowded weekends.',
        severity: 'MEDIUM',
        category: 'SAFETY',
        station: 'Edapally',
        recommendedMitigation: 'Tighten comb plate screws and certify micro-switch trip circuit.',
        sourceReference: 'Page 6, Safety Recommendation',
      },
    ],
    rawContentSnippet: 'QUARTERLY REPORT: Escalator maintenance at Edapally Station. Escalator E3 comb plate safety trip requires recalibration within 7 days.',
  },
  {
    id: 'DOC-KMRL-2026-005',
    title: 'Emergency Evacuation & Tunnel Ventilation Guideline (Revision 2026)',
    fileName: 'KMRL_SFT_EVAC_POLICY_2026.pdf',
    fileType: 'PDF',
    fileSize: '5.4 MB',
    department: 'Safety',
    language: 'English',
    aiPriority: 'CRITICAL',
    status: 'PROCESSED',
    aiConfidence: 99,
    aiPriorityReason: 'New corporate safety policy establishing 30-day mandatory inspection cycle for emergency exit doors and tunnel booster fans across all 25 stations.',
    summary: 'Revised 2026 Comprehensive Safety Standard superseding 2024 directives. Changes mandatory maintenance intervals for tunnel ventilation dampers from 45 days down to 30 days due to monsoon high-humidity corrosion.',
    keyFacts: [
      'Replaces KMRL Safety Directive No. 42 (2024)',
      'Inspection interval shortened from 45 days to 30 days',
      'Mandatory emergency lighting battery discharge test every 15 days',
      'Creates operational policy conflict with vendor service contract KMRL-VND-2024-11',
    ],
    receivedDate: '2026-09-05T09:00:00Z',
    createdDate: '2026-09-05T08:30:00Z',
    submissionDeadline: '2026-09-15T18:00:00Z',
    expectedCompletion: '2026-09-20T18:00:00Z',
    assignedTo: 'K. S. Narayanan',
    riskScore: 89,
    station: 'All Stations',
    storagePath: 'Safety/2026/KMRL_SFT_EVAC_POLICY_2026.pdf',
    versions: [
      { version: 'v1.0', year: '2024', requirement: 'Tunnel damper inspection every 45 days; battery test monthly.' },
      { version: 'v2.0', year: '2025', requirement: 'Tunnel damper inspection every 30 days during monsoon only.' },
      { version: 'v3.0', year: '2026', requirement: 'Mandatory tunnel damper inspection every 30 days year-round; battery discharge test every 15 days.' },
    ],
    timeline: [
      { date: '05 Sep 2026, 09:00 AM', stage: 'Board Approval', description: 'Ratified by KMRL Safety Advisory Council', status: 'completed' },
      { date: '05 Sep 2026, 09:15 AM', stage: 'AI Conflict Analysis', description: 'Flagged 15-day contradiction against Vendor Service SLA', status: 'completed' },
      { date: '15 Sep 2026, 06:00 PM', stage: 'Station Compliance Audit', description: 'All Station Controllers must submit revised roster', status: 'current' },
    ],
    entities: [
      { id: 'ENT-17', name: 'Safety Directorate', type: 'DEPARTMENT', occurrences: 25 },
      { id: 'ENT-18', name: 'Tunnel Ventilation System (TVS)', type: 'ASSET', occurrences: 14 },
      { id: 'ENT-19', name: 'Safety Directive 42/2024', type: 'POLICY', occurrences: 8 },
    ],
    actions: [
      {
        id: 'ACT-006',
        task: 'Issue revised 30-day inspection rosters to all 25 station safety marshals',
        department: 'Safety',
        assignedPerson: 'K. S. Narayanan',
        priority: 'CRITICAL',
        deadline: '2026-09-15T18:00:00Z',
        status: 'IN_PROGRESS',
        evidenceRequired: 'Station marshal acknowledgment receipts & updated CMMS schedule',
        sourceReference: 'Page 2, Section 1.4',
      },
    ],
    risks: [
      {
        id: 'RSK-005',
        title: 'Policy Contradiction with Maintenance SLA',
        description: 'Vendor currently contracted for 45-day cycle. 15-day gap without maintenance coverage.',
        severity: 'CRITICAL',
        category: 'COMPLIANCE',
        recommendedMitigation: 'Execute contractual addendum with Siemens Building Automation within 7 business days.',
        sourceReference: 'Page 9, Compliance Annexure',
      },
    ],
    conflicts: [
      {
        id: 'CONF-001',
        documentAId: 'DOC-KMRL-2026-005',
        documentAName: 'Emergency Evacuation & Tunnel Ventilation Guideline (Revision 2026)',
        documentARequirement: 'Mandatory physical inspection of tunnel booster fans and ventilation dampers every 30 days.',
        documentBId: 'DOC-KMRL-2024-042',
        documentBName: 'KMRL Operations Manual & Maintenance SLA (Directive 42/2024)',
        documentBRequirement: 'Quarterly ventilation dampers maintenance executed every 45 calendar days.',
        conflictType: 'FREQUENCY_MISMATCH',
        recommendedResolution: 'Formally endorse 2026 revision as governing standard and issue contractual SLA amendment to facility contractors.',
        detectedAt: '2026-09-05T09:15:00Z',
      },
    ],
    rawContentSnippet: 'POLICY DIRECTIVE: All stations must maintain 30-day inspection cycle for emergency exit doors and tunnel damper systems. Replaces previous 45-day stipulation.',
  },
  {
    id: 'DOC-KMRL-2026-006',
    title: 'Signaling & Interlocking CBTC System Firmware Upgrade Notice',
    fileName: 'KMRL_SNG_CBTC_FIRMWARE_V4.pdf',
    fileType: 'PDF',
    fileSize: '4.2 MB',
    department: 'Engineering',
    language: 'English',
    aiPriority: 'HIGH',
    status: 'PROCESSED',
    aiConfidence: 96,
    aiPriorityReason: 'Alstom Urbalis 400 CBTC signaling update resolving zone controller failover heartbeat timeouts on Petta-Thykoodam section.',
    summary: 'Software release note and safety case for Zone Controller Firmware v4.2.1. Addresses minor intermittent latency spikes during high-frequency train headway operations near Petta crossover.',
    keyFacts: [
      'Alstom Urbalis 400 CBTC architecture',
      'Target section: Petta to Thykoodam interlocking zones',
      'Testing requires 2 consecutive non-revenue night trials',
      'CMRS clearance required before live deployment',
    ],
    receivedDate: '2026-09-04T15:00:00Z',
    createdDate: '2026-09-04T14:00:00Z',
    submissionDeadline: '2026-09-12T12:00:00Z',
    expectedCompletion: '2026-09-13T06:00:00Z',
    assignedTo: 'Mathew Thomas',
    riskScore: 78,
    station: 'Petta',
    storagePath: 'Engineering/2026/KMRL_SNG_CBTC_FIRMWARE_V4.pdf',
    timeline: [
      { date: '04 Sep 2026, 03:00 PM', stage: 'Vendor Release', description: 'Firmware package received from Alstom Transport', status: 'completed' },
      { date: '04 Sep 2026, 03:30 PM', stage: 'AI Dependency Check', description: 'Verified compatibility with on-board ATC units', status: 'completed' },
      { date: '12 Sep 2026, 12:00 PM', stage: 'Simulation Deadline', description: 'Test bench validation results submission', status: 'current' },
    ],
    entities: [
      { id: 'ENT-20', name: 'Petta Station', type: 'STATION', occurrences: 14 },
      { id: 'ENT-21', name: 'Alstom Transport India', type: 'DEPARTMENT', occurrences: 8 },
      { id: 'ENT-22', name: 'CBTC Zone Controller', type: 'ASSET', occurrences: 19 },
    ],
    actions: [
      {
        id: 'ACT-007',
        task: 'Execute shadow simulator run of Zone Controller patch v4.2.1 at Operations Control Center (OCC)',
        department: 'Engineering',
        assignedPerson: 'Mathew Thomas',
        priority: 'HIGH',
        deadline: '2026-09-12T12:00:00Z',
        status: 'PENDING',
        evidenceRequired: 'Simulator failover log files showing zero packet drop across 100 virtual train insertions',
        sourceReference: 'Page 8, Protocol 4.1',
      },
    ],
    risks: [
      {
        id: 'RSK-006',
        title: 'Emergency Brake Intervention during Revenue Service',
        description: 'Improper patch deployment could trigger fail-safe emergency stops at Petta junction.',
        severity: 'HIGH',
        category: 'OPERATIONAL',
        station: 'Petta',
        recommendedMitigation: 'Enforce dual verification with Alstom signaling specialist present on-site during rollout.',
        sourceReference: 'Page 11, Risk Matrix',
      },
    ],
    rawContentSnippet: 'TECHNICAL NOTICE: Mandatory upgrade of Alstom Urbalis CBTC firmware. Target interlocking: Petta. All simulation validation tests must conclude by 12 September.',
  },
  {
    id: 'DOC-KMRL-2026-007',
    title: 'എം.ജി റോഡ് സ്റ്റേഷൻ വാണിജ്യ വാടക കുടിശ്ശിക ഓഡിറ്റ് റിപ്പോർട്ട് (MG Road Commercial Revenue Audit)',
    fileName: 'KMRL_FIN_MGROAD_COMMERCIAL_ML.pdf',
    fileType: 'PDF',
    fileSize: '2.8 MB',
    department: 'Finance',
    language: 'Malayalam',
    aiPriority: 'MEDIUM',
    status: 'PROCESSED',
    aiConfidence: 93,
    aiPriorityReason: 'Financial internal audit revealing overdue kiosk license fees totaling ₹18.4 Lakhs at MG Road Station concourse retail spaces.',
    summary: 'എം.ജി റോഡ് മെട്രോ സ്റ്റേഷനിലെ 8 റീട്ടെയിൽ ഔട്ട്‌ലെറ്റുകൾ കഴിഞ്ഞ 3 മാസമായി വാടകയും വൈദ്യുതി ചാർജ്ജും അടയ്ക്കാത്തതിനെത്തുടർന്ന് അടിയന്തിര റിക്കവറി നോട്ടീസ് അയക്കാനുള്ള ധനകാര്യ വിഭാഗത്തിന്റെ ശുപാർശ.',
    keyFacts: [
      'Overdue arrears: ₹18,42,500 across 8 commercial vendors',
      'Defaulters include Food Court Unit 3 and Retail Bay 5',
      'Grace period expired on 31 August 2026',
      'Recommended action: 7-day show-cause notice before security forfeiture',
    ],
    receivedDate: '2026-09-03T10:00:00Z',
    createdDate: '2026-09-03T09:00:00Z',
    submissionDeadline: '2026-09-13T17:00:00Z',
    expectedCompletion: '2026-09-15T18:00:00Z',
    assignedTo: 'Lakshmi Nair',
    riskScore: 56,
    station: 'MG Road',
    storagePath: 'Finance/2026/KMRL_FIN_MGROAD_COMMERCIAL_ML.pdf',
    timeline: [
      { date: '03 Sep 2026, 10:00 AM', stage: 'Audit Submission', description: 'Internal Revenue Auditor Report filed', status: 'completed' },
      { date: '03 Sep 2026, 10:15 AM', stage: 'AI Entity Parsing', description: 'Identified 8 delinquent vendor GSTIN records', status: 'completed' },
      { date: '13 Sep 2026, 05:00 PM', stage: 'Statutory Notice Deadline', description: 'Issue formal legal demand under KMRL Commercial By-laws', status: 'current' },
    ],
    entities: [
      { id: 'ENT-23', name: 'MG Road Station', type: 'STATION', occurrences: 16 },
      { id: 'ENT-24', name: 'Finance Directorate', type: 'DEPARTMENT', occurrences: 14 },
      { id: 'ENT-25', name: 'Commercial Kiosks Bay 5', type: 'ASSET', occurrences: 6 },
    ],
    actions: [
      {
        id: 'ACT-008',
        task: 'Issue formal 7-day revenue recovery notices to defaulted retail tenants at MG Road Station',
        department: 'Finance',
        assignedPerson: 'Lakshmi Nair',
        priority: 'MEDIUM',
        deadline: '2026-09-13T17:00:00Z',
        status: 'PENDING',
        evidenceRequired: 'Registered speed post receipts and digital portal demand letter copies',
        sourceReference: 'Page 4, Table 2 (Malayalam Audit)',
      },
    ],
    risks: [
      {
        id: 'RSK-007',
        title: 'Non-fare Revenue Shortfall & Bad Debt',
        description: 'Commercial concessionaires operating without valid bank guarantees.',
        severity: 'MEDIUM',
        category: 'FINANCIAL',
        station: 'MG Road',
        recommendedMitigation: 'Enforce automated bank guarantee renewal alerts and auto-debit escrow mandates.',
        sourceReference: 'Page 5, Auditor Note',
      },
    ],
    rawContentSnippet: 'ധനകാര്യ റിപ്പോർട്ട്: എം.ജി റോഡ് സ്റ്റേഷനിലെ വാടക കുടിശ്ശിക ഉടൻ പിരിച്ചെടുക്കുക. സെപ്റ്റംബർ 13-നകം നോട്ടീസ് അയക്കുക.',
  },
  {
    id: 'DOC-KMRL-2026-008',
    title: 'Water Metro Boat Jetty Gangway Structural Load Certification (High Court Jetty)',
    fileName: 'KMRL_WM_JETTY_STRUCTURAL_2026.pdf',
    fileType: 'PDF',
    fileSize: '5.7 MB',
    department: 'Engineering',
    language: 'English',
    aiPriority: 'HIGH',
    status: 'PROCESSED',
    aiConfidence: 96,
    aiPriorityReason: 'Kochi Water Metro pontoon floating gangway articulation pin inspection showing saltwater tidal corrosion exceeding 2.2mm at High Court terminal.',
    summary: 'IIT Madras Ocean Engineering Department structural health assessment of Kochi Water Metro High Court floating pontoon. Recommended immediate replacement of marine-grade stainless steel articulation pins before festival crowds.',
    keyFacts: [
      'Water Metro High Court terminal pontoon gangway',
      'Daily footfall: 6,800 commuters (connecting Vypeen & Bolgatty)',
      'Articulation hinge pin pin-hole wear measured at 2.4mm (allowable: 1.5mm)',
      'Deadline: 16 September 2026',
    ],
    receivedDate: '2026-09-02T14:00:00Z',
    createdDate: '2026-09-02T12:00:00Z',
    submissionDeadline: '2026-09-16T18:00:00Z',
    expectedCompletion: '2026-09-17T18:00:00Z',
    assignedTo: 'Vinod Krishnan',
    riskScore: 76,
    station: 'High Court Jetty',
    storagePath: 'Engineering/2026/KMRL_WM_JETTY_STRUCTURAL_2026.pdf',
    timeline: [
      { date: '02 Sep 2026, 02:00 PM', stage: 'Report Received', description: 'IIT Madras Ocean Engineering consultancy report', status: 'completed' },
      { date: '02 Sep 2026, 02:10 PM', stage: 'AI Hazard Flagging', description: 'Elevated priority due to public marine walkway', status: 'completed' },
      { date: '16 Sep 2026, 06:00 PM', stage: 'Pin Overhaul Target', description: 'Replacement with 316L stainless steel pins', status: 'current' },
    ],
    entities: [
      { id: 'ENT-26', name: 'High Court Jetty', type: 'STATION', occurrences: 22 },
      { id: 'ENT-27', name: 'Kochi Water Metro', type: 'DEPARTMENT', occurrences: 15 },
      { id: 'ENT-28', name: 'IIT Madras Consultancy', type: 'POLICY', occurrences: 7 },
    ],
    actions: [
      {
        id: 'ACT-009',
        task: 'Procure and install 316L marine-grade stainless steel hinge pins on High Court pontoon gangway',
        department: 'Engineering',
        assignedPerson: 'Vinod Krishnan',
        priority: 'HIGH',
        deadline: '2026-09-16T18:00:00Z',
        status: 'PENDING',
        evidenceRequired: 'Material test certificate (MTC) and ultrasonic weld inspection report',
        sourceReference: 'Page 9, Section 5.3',
      },
    ],
    risks: [
      {
        id: 'RSK-008',
        title: 'Pontoon Gangway Structural Instability during High Tide Surge',
        description: 'Worn articulation pin could jam during rapid tidal fluctuation.',
        severity: 'HIGH',
        category: 'SAFETY',
        station: 'High Court Jetty',
        recommendedMitigation: 'Install temporary secondary safety cable sling until pin replacement is verified.',
        sourceReference: 'Page 3, Structural Summary',
      },
    ],
    rawContentSnippet: 'STRUCTURAL REPORT: Marine gangway at High Court Water Metro Jetty requires pin replacement within 14 days due to saltwater corrosion.',
  },
  {
    id: 'DOC-KMRL-2026-009',
    title: 'Procurement Tender for Heavy-Duty Diamond Rail Crossing Turnouts',
    fileName: 'KMRL_PRO_TURNOUT_TENDER_2026.pdf',
    fileType: 'PDF',
    fileSize: '7.3 MB',
    department: 'Procurement',
    language: 'English',
    aiPriority: 'INFORMATIONAL',
    status: 'PROCESSED',
    aiConfidence: 99,
    aiPriorityReason: 'Standard competitive e-tender publication for 1 in 9 curved UIC 60kg rail turnouts for Phase 1B extension to Tripunithura.',
    summary: 'Global tender notice for supply of 12 sets of thick-web diamond rail crossings and point machines. Bid submission window open for 45 calendar days.',
    keyFacts: [
      'Estimated contract value: ₹8.45 Crores',
      'Technical specification: IRS T-12 60kg 1080 grade head-hardened rails',
      'Pre-bid conference date: 22 September 2026',
      'Bid closing date: 25 October 2026',
    ],
    receivedDate: '2026-09-01T09:30:00Z',
    createdDate: '2026-09-01T09:00:00Z',
    submissionDeadline: '2026-10-25T15:00:00Z',
    expectedCompletion: '2026-11-15T18:00:00Z',
    assignedTo: 'M. Haridas',
    riskScore: 22,
    station: 'Tripunithura',
    storagePath: 'Procurement/2026/KMRL_PRO_TURNOUT_TENDER_2026.pdf',
    timeline: [
      { date: '01 Sep 2026, 09:30 AM', stage: 'Tender Published', description: 'Released on Kerala e-Procurement Portal', status: 'completed' },
      { date: '22 Sep 2026, 11:00 AM', stage: 'Pre-Bid Meeting', description: 'Virtual conference with global suppliers', status: 'pending' },
      { date: '25 Oct 2026, 03:00 PM', stage: 'Bid Submission Close', description: 'Commercial tender opening', status: 'pending' },
    ],
    entities: [
      { id: 'ENT-29', name: 'Tripunithura Station', type: 'STATION', occurrences: 9 },
      { id: 'ENT-30', name: 'Procurement Directorate', type: 'DEPARTMENT', occurrences: 18 },
      { id: 'ENT-31', name: 'RDSO UIC-60 Standard', type: 'POLICY', occurrences: 12 },
    ],
    actions: [
      {
        id: 'ACT-010',
        task: 'Consolidate vendor technical clarification queries for Pre-Bid Conference',
        department: 'Procurement',
        assignedPerson: 'M. Haridas',
        priority: 'LOW',
        deadline: '2026-09-21T17:00:00Z',
        status: 'PENDING',
        evidenceRequired: 'Published Corrigendum-1 on Kerala e-Tenders website',
        sourceReference: 'Page 14, Tender Instructions',
      },
    ],
    risks: [
      {
        id: 'RSK-009',
        title: 'Turnout Supply Delay Impacting Phase 1B Commissioning',
        description: 'Long lead time (18 weeks) from European rail manufacturers.',
        severity: 'LOW',
        category: 'OPERATIONAL',
        station: 'Tripunithura',
        recommendedMitigation: 'Incorporate penalty clauses for supply milestone slippage.',
        sourceReference: 'Page 18, Commercial Terms',
      },
    ],
    rawContentSnippet: 'TENDER INVITATION: Supply of turnout rail sets for KMRL. Pre-bid queries due before 21 September.',
  },
  {
    id: 'DOC-KMRL-2026-010',
    title: 'ആലുവ - ഇടപ്പള്ളി സെക്ഷൻ രാത്രികാല ട്രാക്ക് ജോമെട്രി പരിശോധന (Aluva-Edapally Track Geometry Audit)',
    fileName: 'KMRL_ENG_TRACK_GEOMETRY_ML.pdf',
    fileType: 'PDF',
    fileSize: '4.1 MB',
    department: 'Engineering',
    language: 'Bilingual (EN/ML)',
    aiPriority: 'HIGH',
    status: 'PROCESSED',
    aiConfidence: 96,
    aiPriorityReason: 'Track recording car (TRC) automated laser run detected cross-level twist anomaly of 3.8mm/m near Kalamassery curve (exceeding 3.0mm maintenance limit).',
    summary: 'ആലുവയ്ക്കും ഇടപ്പള്ളിക്കും ഇടയിലുള്ള കൺവഷണൽ ട്രാക്ക് റെക്കോർഡിംഗ് കാർ ഡാറ്റ. കളമശ്ശേരി വളവിൽ ക്രോസ്-ലെവൽ വ്യതിയാനം കണ്ടെത്തി. ട്രെയിനുകളുടെ സുഗമമായ ഓട്ടത്തിന് ട്രാമ്പ് ടാമ്പിംഗ് ഉടൻ പൂർത്തിയാക്കണം.',
    keyFacts: [
      'Twist anomaly location: Km 8/400 to 8/480 near Kalamassery Metro Station',
      'Measured twist: 3.8 mm per meter (Allowable limit: 3.0 mm/m)',
      'Ride index degradation from 2.1 to 2.8',
      'Deadline for tamping machine run: 12 September 2026',
    ],
    receivedDate: '2026-09-08T06:00:00Z',
    createdDate: '2026-09-08T04:30:00Z',
    submissionDeadline: '2026-09-12T05:00:00Z',
    expectedCompletion: '2026-09-12T06:00:00Z',
    assignedTo: 'Anand Varma',
    riskScore: 84,
    station: 'Aluva',
    storagePath: 'Engineering/2026/KMRL_ENG_TRACK_GEOMETRY_ML.pdf',
    timeline: [
      { date: '08 Sep 2026, 06:00 AM', stage: 'TRC Data Download', description: 'Laser track geometry measurements logged', status: 'completed' },
      { date: '08 Sep 2026, 06:10 AM', stage: 'AI Twist Detection', description: 'Exceeded maintenance threshold by 26%', status: 'completed' },
      { date: '12 Sep 2026, 05:00 AM', stage: 'Track Tamping Deadline', description: 'Night machine run and verification check', status: 'current' },
    ],
    entities: [
      { id: 'ENT-32', name: 'Aluva Station', type: 'STATION', occurrences: 11 },
      { id: 'ENT-33', name: 'Edapally Station', type: 'STATION', occurrences: 10 },
      { id: 'ENT-34', name: 'Track Recording Car 02', type: 'EQUIPMENT', occurrences: 8 },
    ],
    actions: [
      {
        id: 'ACT-011',
        task: 'Mobilize Plasser track tamping machine to correct 3.8mm/m twist near Kalamassery curve',
        department: 'Engineering',
        assignedPerson: 'Anand Varma',
        priority: 'HIGH',
        deadline: '2026-09-12T05:00:00Z',
        status: 'IN_PROGRESS',
        evidenceRequired: 'Post-tamping digital chord printout and ride index verification report',
        sourceReference: 'Page 5, Chart 3B (Malayalam Annotation)',
      },
    ],
    risks: [
      {
        id: 'RSK-010',
        title: 'Passenger Discomfort & Flange Wear on Kalamassery Curve',
        description: 'Track twist induces lateral wheel flange acceleration on bogie wheels.',
        severity: 'HIGH',
        category: 'SAFETY',
        station: 'Aluva',
        recommendedMitigation: 'Impose temporary 45 km/h speed restriction on curve until tamping is verified.',
        sourceReference: 'Page 2, Summary Recommendation',
      },
    ],
    rawContentSnippet: 'ട്രാക്ക് ഓഡിറ്റ്: കളമശ്ശേരി വളവിൽ ക്രോസ്-ലെവൽ വ്യതിയാനം. സെപ്റ്റംബർ 12-നകം ടാമ്പിംഗ് യന്ത്രം ഉപയോഗിച്ച് ശരിയാക്കുക.',
  },
  // Adding realistic documents 11 to 30 to satisfy the mandatory 30+ documents requirement:
  ...Array.from({ length: 20 }, (_, idx) => {
    const num = idx + 11;
    const stations = ['Aluva', 'Edapally', 'MG Road', 'Kaloor Stadium', 'Petta', 'Muttom Depot', 'Palarivattom', 'JLN Stadium'];
    const depts: any[] = ['Safety', 'Engineering', 'Operations', 'Finance', 'HR', 'Legal', 'Procurement', 'Maintenance'];
    const priorities: any[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL'];
    const stn = stations[idx % stations.length];
    const dept = depts[idx % depts.length];
    const prio = priorities[idx % priorities.length];
    const daysOffset = (idx % 7) - 2; // Some overdue, some due today, some upcoming
    const deadDate = new Date();
    deadDate.setDate(deadDate.getDate() + daysOffset);

    return {
      id: `DOC-KMRL-2026-0${num}`,
      title: `${stn} ${dept} Operational Directive & Performance Review ${num}`,
      fileName: `KMRL_${dept.substring(0, 3).toUpperCase()}_${stn.replace(' ', '_').toUpperCase()}_${num}.pdf`,
      fileType: (['PDF', 'DOCX', 'XLSX'][idx % 3]) as any,
      fileSize: `${(2.1 + (idx * 0.3)).toFixed(1)} MB`,
      department: dept,
      language: (idx % 4 === 0 ? 'Malayalam' : idx % 5 === 0 ? 'Bilingual (EN/ML)' : 'English') as any,
      aiPriority: prio,
      status: 'PROCESSED' as any,
      aiConfidence: 91 + (idx % 8),
      aiPriorityReason: `Operational analysis identifies mandatory inspection protocols for ${stn} facility under ${dept} regulations.`,
      summary: `Standardized operational compliance document for ${stn} station concerning ${dept.toLowerCase()} infrastructure parameters and scheduled audits.`,
      keyFacts: [
        `Operational facility: ${stn} Metro Station`,
        `Directing Authority: KMRL ${dept} Division`,
        `Mandatory regulatory standard review`,
        `Scheduled action items identified for dispatch`,
      ],
      receivedDate: '2026-09-07T08:00:00Z',
      createdDate: '2026-09-07T07:30:00Z',
      submissionDeadline: deadDate.toISOString(),
      expectedCompletion: new Date(deadDate.getTime() + 86400000).toISOString(),
      assignedTo: ['S. Pradeep', 'Rajesh Kumar Nair', 'Anand Varma', 'Geetha P.', 'Mathew Thomas', 'Deepa Menon'][idx % 6],
      riskScore: prio === 'CRITICAL' ? 92 : prio === 'HIGH' ? 76 : prio === 'MEDIUM' ? 52 : 28,
      station: stn,
      storagePath: `${dept}/2026/KMRL_${dept.substring(0, 3).toUpperCase()}_${num}.pdf`,
      timeline: [
        { date: '07 Sep 2026', stage: 'Document Ingested', description: 'Parsed and metadata cataloged', status: 'completed' as const },
        { date: deadDate.toLocaleDateString(), stage: 'Statutory Target', description: 'Action item resolution deadline', status: 'current' as const },
      ],
      entities: [
        { id: `ENT-${num}-1`, name: `${stn} Station`, type: 'STATION' as const, occurrences: 12 },
        { id: `ENT-${num}-2`, name: `${dept} Directorate`, type: 'DEPARTMENT' as const, occurrences: 8 },
      ],
      actions: [
        {
          id: `ACT-0${num}`,
          task: `Execute scheduled ${dept.toLowerCase()} compliance protocol at ${stn}`,
          department: dept,
          assignedPerson: ['S. Pradeep', 'Rajesh Kumar Nair', 'Anand Varma', 'Geetha P.'][idx % 4],
          priority: prio,
          deadline: deadDate.toISOString(),
          status: (daysOffset < 0 ? 'OVERDUE' : daysOffset === 0 ? 'PENDING' : 'IN_PROGRESS') as any,
          evidenceRequired: 'Field verification photograph & signed job card',
          sourceReference: 'Clause 2.1',
        },
      ],
      risks: [
        {
          id: `RSK-0${num}`,
          title: `${stn} ${dept} Maintenance Deficiency Risk`,
          description: `Deviation from operational maintenance interval at ${stn}.`,
          severity: (prio === 'CRITICAL' ? 'CRITICAL' : prio === 'HIGH' ? 'HIGH' : 'MEDIUM') as RiskSeverity,
          category: (dept === 'Safety' ? 'SAFETY' : dept === 'Engineering' ? 'INFRASTRUCTURE' : 'OPERATIONAL') as RiskCategory,
          station: stn,
          recommendedMitigation: `Complete field inspection and file digital report to ${dept} division.`,
          sourceReference: 'Section 4',
        },
      ],
      rawContentSnippet: `KMRL ${dept} compliance record for ${stn}. Action required according to technical manual.`,
    };
  }),
];

export const INITIAL_TASKS: TaskItem[] = [
  {
    id: 'ACT-001',
    title: 'Execute pressure sensor recalibration on Aluva Concourse Line 2',
    sourceDocumentId: 'DOC-KMRL-2026-001',
    sourceDocumentName: 'KMRL_SFT_ALUVA_FIRE_2026.pdf',
    department: 'Safety',
    assignedPerson: 'S. Pradeep',
    priority: 'CRITICAL',
    createdDate: '2026-09-08T10:35:00Z',
    deadline: '2026-09-10T12:00:00Z',
    status: 'IN_PROGRESS',
    station: 'Aluva',
  },
  {
    id: 'ACT-002',
    title: 'Conduct joint physical inspection with Ernakulam Fire Station Officer',
    sourceDocumentId: 'DOC-KMRL-2026-001',
    sourceDocumentName: 'KMRL_SFT_ALUVA_FIRE_2026.pdf',
    department: 'Operations',
    assignedPerson: 'Deepa Menon',
    priority: 'HIGH',
    createdDate: '2026-09-08T10:35:00Z',
    deadline: '2026-09-10T16:00:00Z',
    status: 'PENDING',
    station: 'Aluva',
  },
  {
    id: 'ACT-003',
    title: 'Replace composite brake pad assemblies on Trainset 07 (Axles 1-6)',
    sourceDocumentId: 'DOC-KMRL-2026-002',
    sourceDocumentName: 'KMRL_RS_BRAKE_CIRCULAR_ML.pdf',
    department: 'Maintenance',
    assignedPerson: 'Rajesh Kumar Nair',
    priority: 'HIGH',
    createdDate: '2026-09-08T14:20:00Z',
    deadline: '2026-09-11T17:00:00Z',
    status: 'IN_PROGRESS',
    station: 'Muttom Depot',
  },
  {
    id: 'ACT-004',
    title: 'Execute night ultrasonic test on 25kV tension insulator span 126/14',
    sourceDocumentId: 'DOC-KMRL-2026-003',
    sourceDocumentName: 'KMRL_ENG_CATENARY_25KV_2026.pdf',
    department: 'Engineering',
    assignedPerson: 'Anand Varma',
    priority: 'CRITICAL',
    createdDate: '2026-09-07T18:30:00Z',
    deadline: '2026-09-10T04:00:00Z',
    status: 'IN_PROGRESS',
    station: 'Kaloor Stadium',
  },
  {
    id: 'ACT-005',
    title: 'Replace comb plate micro-switch and adjust safety skirt gap on Escalator 03',
    sourceDocumentId: 'DOC-KMRL-2026-004',
    sourceDocumentName: 'KMRL_OPS_EDAPALLY_ESCALATOR_2026.pdf',
    department: 'Operations',
    assignedPerson: 'Geetha P.',
    priority: 'MEDIUM',
    createdDate: '2026-09-06T11:10:00Z',
    deadline: '2026-09-14T17:00:00Z',
    status: 'PENDING',
    station: 'Edapally',
  },
  {
    id: 'ACT-006',
    title: 'Issue revised 30-day inspection rosters to all 25 station safety marshals',
    sourceDocumentId: 'DOC-KMRL-2026-005',
    sourceDocumentName: 'KMRL_SFT_EVAC_POLICY_2026.pdf',
    department: 'Safety',
    assignedPerson: 'K. S. Narayanan',
    priority: 'CRITICAL',
    createdDate: '2026-09-05T09:30:00Z',
    deadline: '2026-09-15T18:00:00Z',
    status: 'IN_PROGRESS',
    station: 'All Stations',
  },
  {
    id: 'ACT-007',
    title: 'Execute shadow simulator run of Zone Controller patch v4.2.1 at OCC',
    sourceDocumentId: 'DOC-KMRL-2026-006',
    sourceDocumentName: 'KMRL_SNG_CBTC_FIRMWARE_V4.pdf',
    department: 'Engineering',
    assignedPerson: 'Mathew Thomas',
    priority: 'HIGH',
    createdDate: '2026-09-04T15:15:00Z',
    deadline: '2026-09-12T12:00:00Z',
    status: 'PENDING',
    station: 'Petta',
  },
  {
    id: 'ACT-008',
    title: 'Issue formal 7-day revenue recovery notices to defaulted retail tenants at MG Road Station',
    sourceDocumentId: 'DOC-KMRL-2026-007',
    sourceDocumentName: 'KMRL_FIN_MGROAD_COMMERCIAL_ML.pdf',
    department: 'Finance',
    assignedPerson: 'Lakshmi Nair',
    priority: 'MEDIUM',
    createdDate: '2026-09-03T10:20:00Z',
    deadline: '2026-09-13T17:00:00Z',
    status: 'PENDING',
    station: 'MG Road',
  },
  {
    id: 'ACT-009',
    title: 'Procure and install 316L marine-grade stainless steel hinge pins on High Court pontoon',
    sourceDocumentId: 'DOC-KMRL-2026-008',
    sourceDocumentName: 'KMRL_WM_JETTY_STRUCTURAL_2026.pdf',
    department: 'Engineering',
    assignedPerson: 'Vinod Krishnan',
    priority: 'HIGH',
    createdDate: '2026-09-02T14:30:00Z',
    deadline: '2026-09-16T18:00:00Z',
    status: 'PENDING',
    station: 'High Court Jetty',
  },
  {
    id: 'ACT-010',
    title: 'Consolidate vendor technical clarification queries for Pre-Bid Conference',
    sourceDocumentId: 'DOC-KMRL-2026-009',
    sourceDocumentName: 'KMRL_PRO_TURNOUT_TENDER_2026.pdf',
    department: 'Procurement',
    assignedPerson: 'M. Haridas',
    priority: 'LOW',
    createdDate: '2026-09-01T10:00:00Z',
    deadline: '2026-09-21T17:00:00Z',
    status: 'PENDING',
    station: 'Tripunithura',
  },
  {
    id: 'ACT-011',
    title: 'Mobilize Plasser track tamping machine to correct 3.8mm/m twist near Kalamassery curve',
    sourceDocumentId: 'DOC-KMRL-2026-010',
    sourceDocumentName: 'KMRL_ENG_TRACK_GEOMETRY_ML.pdf',
    department: 'Engineering',
    assignedPerson: 'Anand Varma',
    priority: 'HIGH',
    createdDate: '2026-09-08T06:15:00Z',
    deadline: '2026-09-12T05:00:00Z',
    status: 'IN_PROGRESS',
    station: 'Aluva',
  },
  {
    id: 'ACT-012',
    title: 'Rectify CCTV blind spot at Palarivattom Station Ticket Vending Area',
    sourceDocumentId: 'DOC-KMRL-2026-011',
    sourceDocumentName: 'KMRL_SFT_PALARIVATTOM_CCTV.pdf',
    department: 'Safety',
    assignedPerson: 'S. Pradeep',
    priority: 'CRITICAL',
    createdDate: '2026-09-05T08:00:00Z',
    deadline: '2026-09-08T18:00:00Z',
    status: 'OVERDUE',
    station: 'Palarivattom',
  },
  {
    id: 'ACT-013',
    title: 'Submit quarterly diesel generator emissions log to Kerala State Pollution Control Board',
    sourceDocumentId: 'DOC-KMRL-2026-012',
    sourceDocumentName: 'KMRL_ENG_KSPCB_AIR_2026.pdf',
    department: 'Engineering',
    assignedPerson: 'Anand Varma',
    priority: 'HIGH',
    createdDate: '2026-09-06T10:00:00Z',
    deadline: '2026-09-09T18:00:00Z',
    status: 'OVERDUE',
    station: 'Muttom Depot',
  },
  {
    id: 'ACT-014',
    title: 'Replace backup lithium battery bank on UPS-02 at Kaloor Stadium Substation',
    sourceDocumentId: 'DOC-KMRL-2026-013',
    sourceDocumentName: 'KMRL_OPS_UPS_REPLACE_2026.pdf',
    department: 'Operations',
    assignedPerson: 'Geetha P.',
    priority: 'CRITICAL',
    createdDate: '2026-09-07T12:00:00Z',
    deadline: '2026-09-09T23:59:00Z',
    status: 'PENDING',
    station: 'Kaloor Stadium',
  },
  {
    id: 'ACT-015',
    title: 'Verify emergency passenger intercom call boxes at Edapally Station',
    sourceDocumentId: 'DOC-KMRL-2026-014',
    sourceDocumentName: 'KMRL_OPS_PHP_EDAPALLY_2026.pdf',
    department: 'Operations',
    assignedPerson: 'Deepa Menon',
    priority: 'MEDIUM',
    createdDate: '2026-09-08T08:00:00Z',
    deadline: '2026-09-09T18:00:00Z',
    status: 'COMPLETED',
    evidenceFileName: 'PHP_Edapally_Signed_Checklist.pdf',
    evidenceUploadedAt: '2026-09-09T14:30:00Z',
    completionDate: '2026-09-09T14:35:00Z',
    station: 'Edapally',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'NOTIF-001',
    type: 'CRITICAL',
    title: 'Critical Document Received: Aluva Fire Safety Audit',
    message: 'Mandatory sprinkler inspection required within 24 hours. Concourses pressure dropped to 2.1 bar.',
    timestamp: '2026-09-08T10:33:00Z',
    read: false,
    linkTo: '/documents/DOC-KMRL-2026-001',
    targetId: 'DOC-KMRL-2026-001',
  },
  {
    id: 'NOTIF-002',
    type: 'WARNING',
    title: 'Policy Conflict Detected by AI',
    message: 'Contradiction between 2026 Safety Guideline (30-day inspection) and Operations Manual (45-day inspection).',
    timestamp: '2026-09-05T09:15:00Z',
    read: false,
    linkTo: '/conflicts',
    targetId: 'CONF-001',
  },
  {
    id: 'NOTIF-003',
    type: 'CRITICAL',
    title: 'Task Overdue: CCTV Blind Spot at Palarivattom',
    message: 'Safety task ACT-012 was due yesterday. Immediate attention required.',
    timestamp: '2026-09-09T00:01:00Z',
    read: false,
    linkTo: '/actions',
    targetId: 'ACT-012',
  },
  {
    id: 'NOTIF-004',
    type: 'INFO',
    title: 'Bilingual Document Processed',
    message: 'Muttom Depot Brake Pad Directive translated from Malayalam to English with 94% AI confidence.',
    timestamp: '2026-09-08T14:20:00Z',
    read: true,
    linkTo: '/documents/DOC-KMRL-2026-002',
    targetId: 'DOC-KMRL-2026-002',
  },
  {
    id: 'NOTIF-005',
    type: 'SUCCESS',
    title: 'Task Completed: Edapally Intercom Inspection',
    message: 'Officer Deepa Menon submitted verified sign-off checklist.',
    timestamp: '2026-09-09T14:35:00Z',
    read: true,
    linkTo: '/actions',
    targetId: 'ACT-015',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogItem[] = [
  {
    id: 'AUD-001',
    timestamp: '2026-09-09T14:35:00Z',
    actor: 'Deepa Menon',
    role: 'OFFICER',
    action: 'TASK_COMPLETED',
    target: 'ACT-015 (Edapally Intercom Verification)',
    details: 'Uploaded signed evidence file PHP_Edapally_Signed_Checklist.pdf',
    ipAddress: '10.14.22.84',
  },
  {
    id: 'AUD-002',
    timestamp: '2026-09-08T15:20:00Z',
    actor: 'K. S. Narayanan',
    role: 'ADMIN',
    action: 'PRIORITY_OVERRIDE',
    target: 'DOC-KMRL-2026-005',
    details: 'Changed AI priority HIGH -> CRITICAL. Reason: Direct regulatory scrutiny from CMRS.',
    ipAddress: '10.14.0.12',
  },
  {
    id: 'AUD-003',
    timestamp: '2026-09-08T14:20:00Z',
    actor: 'NEXUS AI Pipeline',
    role: 'ADMIN',
    action: 'AUTO_TASK_DISPATCH',
    target: 'ACT-003',
    details: 'Extracted task from Malayalam section of KMRL_RS_BRAKE_CIRCULAR_ML.pdf and routed to Maintenance',
    ipAddress: '127.0.0.1',
  },
  {
    id: 'AUD-004',
    timestamp: '2026-09-08T10:33:00Z',
    actor: 'NEXUS AI Pipeline',
    role: 'ADMIN',
    action: 'AI_CLASSIFICATION',
    target: 'DOC-KMRL-2026-001',
    details: 'Classified as CRITICAL (Confidence: 97%). Triggered automatic task creation ACT-001.',
    ipAddress: '127.0.0.1',
  },
  {
    id: 'AUD-005',
    timestamp: '2026-09-08T10:30:00Z',
    actor: 'S. Pradeep',
    role: 'OFFICER',
    action: 'DOCUMENT_UPLOAD',
    target: 'KMRL_SFT_ALUVA_FIRE_2026.pdf',
    details: 'Uploaded 4.8MB PDF to cloud storage folder: Safety/2026/',
    ipAddress: '10.14.12.55',
  },
];
